CHESS = "CHESS"
XIANGQI = "XIANGQI"

ONLINE = "ONLINE"
FRIEND = "FRIEND"
OFFLINE = "OFFLINE"

BULLET = "BULLET"
BLITZ = "BLITZ"
RAPID = "RAPID"
CLASSICAL = "CLASSICAL"

CHESS_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
XIANGQI_FEN = "rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR  w - - 0 1"